export const
    CANVAS_SIDE_DEFAULT = 400,
    COLOR_ALPHA_MAX = 1,
    COLOR_VAL_MAX = 255,
    COLOR_ALPHA_PRECISION = 100,
    COLOR_DIFFERENCE_DEFAULT = 120,
    SORT_DIR_ASC = 'asc',
    SORT_DIR_DESC = 'desc',
    SORT_TYPE_COUNT = 'count',
    SORT_TYPE_ALPHA = 'alpha';