export const
    COLOR_VAL_MAX = 255,
    COLOR_ALPHA_PRECISION = 100,
    COLOR_DIFFERENCE_DEFAULT = 120,
    READABLE_LUM_DIFF = 5,
    READABLE_ALPHA = .5,
    READABLE_TRY_LIMIT = 100,
    LUM_STEP = .05,
    SORT_DIR_DESC = 'desc',
    SORT_TYPE_COUNT = 'count',
    SORT_TYPE_ALPHA = 'alpha';